spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.198.61:3306/campus_community?useSSL=false
    username: hubert
    password: Iwgmhty-4774747
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  # 保持的最小连接数
    maxActive: 20   # 最大连接数，超过则等待
    maxWait: 10000   # 获取连接等待超时的时间
  # 邮箱
  mail:
    host: smtp.163.com
    port: 465
    default-encoding: UTF-8
    username: hubert137@163.com
    password: JYPXOVWPMMKCTQTC
    protocol: smtps  # 选择加密协议
    properties:
      mail:
        smtp:
          ssl:
            enable: true


# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  #映射文件
  type-aliases-package: com.htc.entity      #实体类包路径
  configuration:
    map-underscore-to-camel-case: true      #数据库字段下划线方式自动映射为驼峰方式

# 日志级别设置
logging:
  config: classpath:log4j2.yaml
#  level:
#    root: warn

server:
  port: 8081